spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/heavenpay?characterEncoding=UTF-8&serverTimezone=UTC&allowMultiQueries=true&autoReconnection=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql : true
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true